name: Frontend Deployment to GCP Linux VM

on:
  push:
    branch:
      -  main

jobs:
  deploy:
    name: Frontend Deployment to GCP Linux VM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#      - uses: google-github-actions/setup-gcloud@main

      - name: Node 12.22.9
        uses: actions/setup-node@v2
        with:
          node-version: 12.22.9

      - name: npm install and npm run build
        run: |
          npm install
          npm run build

      - name: copy files to server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          target: ${{ secrets.TARGET }}
          source: "./dist/*"
          strip-components: 1 # strip components = 1 to remove the dist folder and only copy the files within it
