name: Frontend Deployment to GCP Linux VM

on:
  push:
    branch:
      -  main

jobs:
  deploy:
    name: Frontend Deployment to GCP Linux VM
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
#      - uses: google-github-actions/setup-gcloud@main

      - name: Node 8.10.0
        uses: actions/setup-node@v2
        with:
          node-version: 8.10.0

      - name: npm install and npm run build
        run:
          npm install
          ng build

      - name: copy files to server
        uses: marcbudd/frontend-P2cinema@main
        with:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          target: ${{ secrets.TARGET }}
          source: "./dist/*"
          strip-components: 1 # strip components = 1 to remove the dist folder and only copy the files within it
