name: Frontend Deployment to Linux VM

on:
  push:
    branch:
      -  main

jobs:
  deploy:
    name: Frontend Deployment to Linux VM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node 16.13
        uses: actions/setup-node@v2
        with:
          node-version: 16.13

      - name: npm install and npm run build
        run: |
          npm install
          npm run build

      - name: copy files to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.TARGET }}
            touch test.txt
#            cd /home/${{ secrets.USERNAME }}/
#            mkdir test
#            rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET }}
#          passphrase: ${{ secrets.PASSPHRASE }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          port: ${{ secrets.PORT }}
#          script: whoami
#          target: ${{ secrets.TARGET }}
#          source: "./dist/*"
#          strip-components: 1 # strip components = 1 to remove the dist folder and only copy the files within it
